In [1]:
from sklearn.ensemble import IsolationForest
from sklearn import svm
import pandas as pd
import numpy as np
import sys
import csv

params = {}
params['n_estimators'] = 100
params['max_samples'] ='auto'
params['contamination'] = 0.1
params['max_features'] = 1.0

params['nu'] = 0.001
params['gamma']='auto'
params['kernel'] ='poly'

params['path'] = 'data/train/B01.csv'
params['opath'] ='dataclean/B01.csv'
try:
    with open(params['path'],'r') as f:
        reader = csv.reader(f)
        head_row=next(reader)
        data_attribute = []
    for item in head_row:
        data_attribute.append(item)
    print(data_attribute)
except Exception as e:
    print(e)

['DE_time', 'FE_time', 'BA_time', 'RPM']


In [2]:
tn = pd.read_csv(params['path']) 
tn.dropna(inplace=True)
train = np.array(tn)
train_x = np.array(train)
print(train_x)
# clf = IsolationForest(n_estimators=params['n_estimators'], 
#                       max_samples=params['max_samples'], 
#                       contamination=params['contamination'], 
#                       max_features=params['max_features'], 
#                       bootstrap=False, n_jobs=1, random_state=None, 
#                       verbose=0).fit(train_x)
clf = svm.OneClassSVM(nu=params['nu'],
              kernel=params['kernel'],
              gamma=params['gamma']).fit(train_x)
pred = clf.predict(train_x)
print (pred.size)

[[ 1.91511018e-01 -3.69818182e-02 -8.20842730e-03  1.79600000e+03]
 [ 1.50577365e-01  4.49945455e-02 -1.55316320e-02  1.79600000e+03]
 [-3.68727745e-02 -8.62909091e-03  3.82255193e-03  1.79600000e+03]
 ...
 [ 2.42353214e-01 -6.98545455e-03  7.06970920e-02  1.79600000e+03]
 [ 3.24870259e-03  1.06836364e-02  7.12604154e-02  1.79600000e+03]
 [-6.22126547e-02 -1.01700000e-01 -2.03198813e-02  1.79600000e+03]]
14708


In [7]:
df = pd.DataFrame(pd.read_csv(params['path']))[0:pred.size]
df['pred']=pred
df2 = df[-df.pred.isin([-1])]
df2 = df2.drop(['pred'],axis=1)
data_out = df2.iloc[:,:].values
print(int(df2.size/4))
csvfile2 = open(params['opath'],'w',newline='')
writer = csv.writer(csvfile2)
writer.writerow(data_attribute)   #存属性
m=len(data_out)
for i in range(m):
    writer.writerow(data_out[i])

14708


In [30]:
import pandas as pd
import numpy as np
import os
from scipy import stats,signal,fftpack
import math
from pywt import wavedec
import traceback
import sys
columns_list=['time_mean','time_std','time_max','time_min','time_rms','time_ptp','time_median','time_iqr','time_pr','time_skew','time_kurtosis','time_var','time_amp',                'time_smr','time_wavefactor','time_peakfactor','time_pulse','time_margin','freq_mean','freq_std','freq_max','freq_min','freq_rms','freq_median',               'freq_iqr','freq_pr','freq_f2','freq_f3','freq_f4','freq_f5','freq_f6','freq_f7','freq_f8','ener_cA5','ener_cD1','ener_cD2','ener_cD3','ener_cD4',        'ener_cD5','ratio_cA5','ratio_cD1','ratio_cD2','ratio_cD3','ratio_cD4','ratio_cD5']
columns_list1 = [a + '_DE' for a in columns_list]
columns_list2 = [a + '_FE' for a in columns_list]
# columns_list3 = [a + '_BA' for a in columns_list]
# columns_list_final = columns_list1 + columns_list2+ columns_list3
columns_list_final = columns_list1 + columns_list2
params = {}
params['len_piece']=100 #窗口长度
windowlen=params['len_piece']


def feature_get(filepath,windowlen):
        df_data = pd.DataFrame(pd.read_csv(filepath))
#         dfs = df_data.loc[:,['DE_time','FE_time','BA_time']]
        dfs = df_data.loc[:,['DE_time','FE_time']]
        features_list=[]
        print(len(dfs))
        for i in range (0,len(dfs),windowlen):
            if(int((len(dfs)-i)/100)>=1): #舍去少量数据
                df=dfs[i:i+params['len_piece']]
                feature_list = []
    #             print(df)
                for i in df.columns:
                    #----------  time-domain feature,18
                    #依次为均值，标准差，最大值，最小值，均方根，峰峰值，中位数，四分位差，百分位差，偏度，峰度，方差，整流平均值，方根幅值，波形因子，峰值因子，脉冲值，裕度
                    df_line = df[i]
    #                 print(df_line)
                    time_mean = df_line.mean()
                    time_std = df_line.std()
                    time_max = df_line.max()
                    time_min = df_line.min()
                    time_rms = np.sqrt(np.square(df_line).mean())
                    time_ptp = time_max-time_min 
                    time_median = np.median(df_line)
                    time_iqr = np.percentile(df_line,75)-np.percentile(df_line,25)
                    time_pr = np.percentile(df_line,90)-np.percentile(df_line,10)
                    time_skew = stats.skew(df_line)
                    time_kurtosis = stats.kurtosis(df_line)
                    time_var = np.var(df_line)
                    time_amp = np.abs(df_line).mean()
                    time_smr = np.square(np.sqrt(np.abs(df_line)).mean())
                    #下面四个特征需要注意分母为0或接近0问题，可能会发生报错
                    time_wavefactor = time_rms/time_amp
                    time_peakfactor = time_max/time_rms
                    time_pulse = time_max/time_amp
                    time_margin = time_max/time_smr
                    #----------  freq-domain feature,15
                    #采样频率25600Hz
                    df_fftline = fftpack.fft(df[i])
                    freq_fftline = fftpack.fftfreq(len(df[i]),1/25600)
                    df_fftline = abs(df_fftline[freq_fftline>=0])
                    freq_fftline = freq_fftline[freq_fftline>=0]
                    #基本特征,依次为均值，标准差，最大值，最小值，均方根，中位数，四分位差，百分位差
                    freq_mean = df_fftline.mean()
                    freq_std = df_fftline.std()
                    freq_max = df_fftline.max()
                    freq_min = df_fftline.min()
                    freq_rms = np.sqrt(np.square(df_fftline).mean())
                    freq_median = np.median(df_fftline)
                    freq_iqr = np.percentile(df_fftline,75)-np.percentile(df_fftline,25)
                    freq_pr = np.percentile(df_fftline,90)-np.percentile(df_fftline,10)
                    #f2 f3 f4反映频谱集中程度
                    freq_f2 = np.square((df_fftline-freq_mean)).sum()/(len(df_fftline)-1)
                    freq_f3 = pow((df_fftline-freq_mean),3).sum()/(len(df_fftline)*pow(freq_f2,1.5))
                    freq_f4 = pow((df_fftline-freq_mean),4).sum()/(len(df_fftline)*pow(freq_f2,2))
                    #f5 f6 f7 f8反映主频带位置
                    freq_f5 = np.multiply(freq_fftline,df_fftline).sum()/df_fftline.sum()
                    freq_f6 = np.sqrt(np.multiply(np.square(freq_fftline),df_fftline).sum())/df_fftline.sum()
                    freq_f7 = np.sqrt(np.multiply(pow(freq_fftline,4),df_fftline).sum())/np.multiply(np.square(freq_fftline),df_fftline).sum()
                    freq_f8 = np.multiply(np.square(freq_fftline),df_fftline).sum()/np.sqrt(np.multiply(pow(freq_fftline,4),df_fftline).sum()*df_fftline.sum())
                    #----------  timefreq-domain feature,12
                    #5级小波变换，最后输出6个能量特征和其归一化能量特征
                    cA5, cD5, cD4, cD3, cD2, cD1 = wavedec(df[i], 'db10', level=5)
                    ener_cA5 = np.square(cA5).sum()
                    ener_cD5 = np.square(cD5).sum()
                    ener_cD4 = np.square(cD4).sum()
                    ener_cD3 = np.square(cD3).sum()
                    ener_cD2 = np.square(cD2).sum()
                    ener_cD1 = np.square(cD1).sum()
                    ener = ener_cA5 + ener_cD1 + ener_cD2 + ener_cD3 + ener_cD4 + ener_cD5
                    ratio_cA5 = ener_cA5/ener
                    ratio_cD5 = ener_cD5/ener
                    ratio_cD4 = ener_cD4/ener
                    ratio_cD3 = ener_cD3/ener
                    ratio_cD2 = ener_cD2/ener
                    ratio_cD1 = ener_cD1/ener
                    feature_list.extend([time_mean,time_std,time_max,time_min,time_rms,time_ptp,time_median,time_iqr,time_pr,time_skew,time_kurtosis,time_var,time_amp,
                                     time_smr,time_wavefactor,time_peakfactor,time_pulse,time_margin,freq_mean,freq_std,freq_max,freq_min,freq_rms,freq_median,
                                     freq_iqr,freq_pr,freq_f2,freq_f3,freq_f4,freq_f5,freq_f6,freq_f7,freq_f8,ener_cA5,ener_cD1,ener_cD2,ener_cD3,ener_cD4,ener_cD5,
                                     ratio_cA5,ratio_cD1,ratio_cD2,ratio_cD3,ratio_cD4,ratio_cD5])
                features_list.append(feature_list)
        return features_list

# 约定normal(NORMAL), ball(B), outer race(OR), inner race(IR)的预测输出标签为0, 1, 2, 3。
# NORMAL:0
for i in range(1,3):
    params['data_path'] = 'data/train/NORMAL0'+str(i)+'.csv'
    params['opath'] ='datafeature/NORMAL0'+str(i)+'_feature.csv'
    fea = feature_get(params['data_path'],windowlen)
    result = pd.DataFrame(fea,columns = columns_list_final)
    result['label']=0
    result.to_csv(params['opath'],index=False,header=True)

# B:1    
for i in range(1,7):
    params['data_path'] = 'data/train/B0'+str(i)+'.csv'
    params['opath'] ='datafeature/B0'+str(i)+'_feature.csv'
    fea = feature_get(params['data_path'],windowlen)
    result = pd.DataFrame(fea,columns = columns_list_final)
    result['label']=1
    result.to_csv(params['opath'],index=False,header=True)
    
# OR:2    
for i in range(1,15):
    if(i<=9):
        params['data_path'] = 'data/train/OR0'+str(i)+'.csv'
        params['opath'] ='datafeature/OR0'+str(i)+'_feature.csv'
    else:
        params['data_path'] = 'data/train/OR'+str(i)+'.csv'
        params['opath'] ='datafeature/OR'+str(i)+'_feature.csv'        
    fea = feature_get(params['data_path'],windowlen)
    result = pd.DataFrame(fea,columns = columns_list_final)
    result['label']=2
    result.to_csv(params['opath'],index=False,header=True)
    
# IR:3
for i in range(1,7):
    params['data_path'] = 'data/train/IR0'+str(i)+'.csv'
    params['opath'] ='datafeature/IR0'+str(i)+'_feature.csv'
    fea = feature_get(params['data_path'],windowlen)
    result = pd.DataFrame(fea,columns = columns_list_final)
    result['label']=3
    result.to_csv(params['opath'],index=False,header=True)
    

# TEST:-1
for i in range(1,15):
    if(i<=9):
        params['data_path'] = 'data/test/TEST0'+str(i)+'.csv'
        params['opath'] ='testfeature/TEST0'+str(i)+'_feature.csv'
    else:
        params['data_path'] = 'data/test/TEST'+str(i)+'.csv'
        params['opath'] ='testfeature/TEST'+str(i)+'_feature.csv'        
    fea = feature_get(params['data_path'],windowlen)
    result = pd.DataFrame(fea,columns = columns_list_final)
    result['label']=-1
    result.to_csv(params['opath'],index=False,header=True)

print("done")

182953


C:\Users\yjw98\Anaconda3\envs\tensorflow\lib\site-packages\pywt\_multilevel.py:45: UserWarning: Level value of 5 is too high: all coefficients will experience boundary effects.
  "boundary effects.").format(level))


362927
14708
14621
14638
14569
14656
14604
7336
7319
7336
7310
7302
7345
7310
7310
7345
7319
7328
7319
7319
7345
14551
14621
14656
14638
14621
14586
14586
14656
14621
7293
7336
7336
7362
363797
7336
7310
7284
14621
14656
14638
done


In [24]:
import pandas as pd
path = 'datafeature/B01_feature.csv'  #特征提取后的csv文件路径
df = pd.DataFrame(pd.read_csv(path))
delete_features = [] #需要删除的列名自行加到数组里
df = df.drop(delete_features, axis=1) #特征选择之后的数据

In [57]:
import pandas as pd
df1 = pd.read_csv('datafeature/B01_feature.csv')
df2 = pd.read_csv('datafeature/B02_feature.csv')
df3 = pd.read_csv('datafeature/B03_feature.csv')
df4 = pd.read_csv('datafeature/B04_feature.csv')
df5 = pd.read_csv('datafeature/B05_feature.csv')
df_fault = pd.concat([df1,df2,df3,df4,df5])
df_fault = df_fault.reset_index(drop=True)
df_fault.to_csv('data_faultB.csv',index=False)

In [32]:
import os
import pandas as pd
filePath='datafeature'
outputfile='train.csv'
fileList = os.listdir(filePath)
# print(fileList)
# print(len(fileList))
path = os.path.join(filePath, fileList[0])
df = pd.read_csv(path)
df.to_csv(outputfile,index=False, header=True)
for i in range (1,len(fileList)):
    path = os.path.join(filePath, fileList[i])
#     print(path)
    df = pd.read_csv(path)
    df.to_csv(outputfile, mode='a', index=False, header=False)
print("Done.")

Done.


In [48]:
import lightgbm as lgb
import joblib
def train():
    # 模型初始化，设置random_state保证可复现性，便于观察优化
    train_data = pd.read_csv('train.csv')
    train_data_y = train_data['label']
    # 除去标签的所有列就是特征
    train_data_x = train_data.drop(['label'], axis=1)
    model_lgb_default = lgb.LGBMClassifier(learning_rate=0.03,random_state=None)
    # 模型训练
    model_lgb_default.fit(train_data_x, train_data_y)
    joblib.dump(model_lgb_default, 'model/lightgbm_model.model')
    print("Done.")

train()

Done.


In [54]:
import lightgbm as lgb
import joblib
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

def train():
    # 模型初始化，设置random_state保证可复现性，便于观察优化
    train_data = pd.read_csv('train.csv')
    train_data_y = train_data['label']
    # 除去标签的所有列就是特征
    train_data_x = train_data.drop(['label'], axis=1)
    train_x, valid_x, train_y, valid_y = train_test_split(train_data_x, train_data_y, test_size=0.3, random_state=0)
    # 传入到knn进行训练，得到模型
    classifier = KNeighborsClassifier()
    param_dict = {"n_neighbors":[1,3,5,7,9]}
   #加入网格搜索和交叉验证
    classifier = GridSearchCV(classifier,param_grid=param_dict,cv=4)
    classifier.fit(train_x,train_y)
 
    y_predict = classifier.predict(valid_x)
    print("最佳参数 ：",classifier.best_params_)
    print("最佳结果：",classifier.best_score_)
    print("最佳预估器：",classifier.best_estimator_)
    print("交叉验证结果",classifier.cv_results_)
    print("准确度为：", classifier.score(valid_x,valid_y))
    joblib.dump(classifier, 'model/knn.model')
    print("Done.")


train()

最佳参数 ： {'n_neighbors': 7}
最佳结果： 0.9340401871771147
最佳预估器： KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')
交叉验证结果 {'mean_fit_time': array([0.07780004, 0.07829189, 0.07630348, 0.07599342, 0.0755555 ]), 'std_fit_time': array([0.00186594, 0.00226864, 0.00049019, 0.0007767 , 0.00082951]), 'mean_score_time': array([0.07046503, 0.08175719, 0.08277839, 0.08691478, 0.09066445]), 'std_score_time': array([0.00176111, 0.00212599, 0.00070478, 0.0011238 , 0.00081975]), 'param_n_neighbors': masked_array(data=[1, 3, 5, 7, 9],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'n_neighbors': 1}, {'n_neighbors': 3}, {'n_neighbors': 5}, {'n_neighbors': 7}, {'n_neighbors': 9}], 'split0_test_score': array([0.92019431, 0.92643997, 0.92990978, 0.92852186, 0.92852186]), 'split1_test_score': array([0.92986111

In [43]:
# 超参数搜索
import lightgbm as lgb
import joblib
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

def train():
    # 模型初始化，设置random_state保证可复现性，便于观察优化
    train_data = pd.read_csv('train.csv')
    train_data_y = train_data['label']
    # 除去标签的所有列就是特征
    train_data_x = train_data.drop(['label'], axis=1)
    train_x, valid_x, train_y, valid_y = train_test_split(train_data_x, train_data_y, test_size=0.333, random_state=0)
    train = lgb.Dataset(train_x, train_y)
    valid = lgb.Dataset(valid_x, valid_y, reference=train)
    parameters = {
              'max_depth': [15, 20, 25, 30, 35],
              'learning_rate': [0.05, 0.1, 0.15],
              'feature_fraction': [0.6, 0.7, 0.8, 0.9, 0.95],
              'bagging_fraction': [0.6, 0.7, 0.8, 0.9, 0.95],
              'bagging_freq': [2, 4, 5, 6, 8],
              'lambda_l1': [0, 0.1, 0.4, 0.5, 0.6],
              'lambda_l2': [0, 10, 15, 35, 40],
              'cat_smooth': [1, 10, 15, 20, 35]
    }
    gbm = lgb.LGBMClassifier(boosting_type='gbdt',
                         objective = 'binary',
                         metric = 'auc',
                         verbose = 0,
                         learning_rate = 0.01,
                         num_leaves = 35,
                         feature_fraction=0.8,
                         bagging_fraction= 0.9,
                         bagging_freq= 8,
                         lambda_l1= 0.6,
                         lambda_l2= 0)
    gsearch = GridSearchCV(gbm, param_grid=parameters, scoring='accuracy', cv=3)
    gsearch.fit(train_x, train_y)
    print("Best score: %0.3f" % gsearch.best_score_)
    print("Best parameters set:")
    best_parameters = gsearch.best_estimator_.get_params()
    for param_name in sorted(parameters.keys()):
        print("\t%s: %r" % (param_name, best_parameters[param_name]))
#     joblib.dump(model_lgb_default, 'model/lightgbm_model.model')
    print("Done.")

train()

C:\Users\yjw98\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\model_selection\_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
lightgbm.basic.LightGBMError: Multiclass objective and metrics don't match

  FitFailedWarning)


LightGBMError: Multiclass objective and metrics don't match

In [56]:
import lightgbm as lgb
import joblib
import pandas as pd

def judge(input_pred):
    return_pred = list(np.zeros(len(input_pred)))
    for i in range(0, len(input_pred)):
        if (input_pred[i][0] > 0.5):
            return_pred[i] = 0
        elif(input_pred[i][1]>0.5):
            return_pred[i] = 1
        elif(input_pred[i][2]>0.5):
            return_pred[i] = 2
        elif(input_pred[i][3]>0.5):
            return_pred[i] = 3
    return return_pred
    
def score(predlist ,pred):
    # score = [0.3×f1score(class1) + 0.3×f1score(class2) + 0.3×f1score(class3) + 0.1×f1score(class0)]*100
    pass

def test_lightgbm():
    # 加载模型
#     model = joblib.load('model/lightgbm_model.model')
    model = joblib.load('model/knn.model')
    test1=pd.read_csv('testfeature/TEST01_feature.csv')
    test2=pd.read_csv('testfeature/TEST02_feature.csv')
    test3=pd.read_csv('testfeature/TEST03_feature.csv')
    test4=pd.read_csv('testfeature/TEST04_feature.csv')
    test5=pd.read_csv('testfeature/TEST05_feature.csv')
    test6=pd.read_csv('testfeature/TEST06_feature.csv')
    test7=pd.read_csv('testfeature/TEST07_feature.csv')
    test8=pd.read_csv('testfeature/TEST08_feature.csv')
    test9=pd.read_csv('testfeature/TEST09_feature.csv')
    test10=pd.read_csv('testfeature/TEST10_feature.csv')
    test11=pd.read_csv('testfeature/TEST11_feature.csv')
    test12=pd.read_csv('testfeature/TEST12_feature.csv')
    test13=pd.read_csv('testfeature/TEST13_feature.csv')
    test14=pd.read_csv('testfeature/TEST14_feature.csv')
    i=1
    for test_i in [test1,test2,test3,test4,test5,test6,test7,test8,test9,test10,test11,test12,test13,test14]:
        test_name = 'test_' + str(i)
        i+=1
        print('The result of test is:')
        test_j=test_i.drop(['label'], axis=1)
        y_pred = model.predict_proba(test_j)
        y_pred_binary = judge(y_pred)
        predlist=[y_pred_binary.count(0), y_pred_binary.count(1),y_pred_binary.count(2),y_pred_binary.count(3)]
        pred=predlist.index(max(predlist))
        print(test_name,predlist ,pred)


        
test_lightgbm()

The result of test is:
test_1 [2, 142, 0, 1] 1
The result of test is:
test_2 [0, 145, 0, 1] 1
The result of test is:
test_3 [9, 103, 18, 16] 1
The result of test is:
test_4 [0, 0, 59, 13] 2
The result of test is:
test_5 [13, 16, 35, 9] 2
The result of test is:
test_6 [0, 0, 62, 11] 2
The result of test is:
test_7 [3, 25, 28, 17] 2
The result of test is:
test_8 [3637, 0, 0, 0] 0
The result of test is:
test_9 [8, 8, 39, 18] 2
The result of test is:
test_10 [7, 25, 40, 1] 2
The result of test is:
test_11 [0, 0, 71, 1] 2
The result of test is:
test_12 [5, 3, 41, 97] 3
The result of test is:
test_13 [0, 0, 4, 142] 3
The result of test is:
test_14 [2, 102, 40, 2] 1
